project:
  type: website
  output-dir: docs

website:
  back-to-top-navigation: true
  favicon: ðŸŒ¿
  navbar:
    title: false
    left:
    - href: index.qmd
      text: Home
    - href: about.qmd
      text: About
    - href: Projects.qmd #need to change this to Blog one day. and then a separate section to Projects (list of projects)
      text: Blog
    - href: Hamilton_resume_1page_aug27.pdf
      text: Resume
      
    right: 
    - text: Get in Touch!
      menu: 
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/flora-hamilton-946980122/
      - icon: github
        text: GitHub
        href: https://github.com/floraham
    
      
  page-footer:
    background: light # or dark 
    left: 
      - "Copyright 2024, Flora Hamilton"
    right: 
      - This website was built with Quarto
    


format:
  html:
    theme:
      light: mystyles.css
      dark: [cosmo, theme-dark.scss]
    mainfont: Roboto
    toc: false
  
editor: visual

